import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
  return (
    <nav className="flex w-full items-centered justify-between p-4 text-xl border-b font-semibold">
      <div> Gallery </div>

      <div> Sign In</div>
    </nav>
  );
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode 

}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className={'font-sans ${inter.variable} flex flex-col gap-4'}> 
        <TopNav />
        {children}
      </body>
    </html>
  );
}
