import "~/styles/globals.css";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { TopNav } from "./_components/topnav";

export const metadata: Metadata = {
  title: "m3 gallery",
  description: "generated by mehmet",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};




export default function RootLayout({
  children,
}: {
  children: React.ReactNode 

}) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className={'font-sans ${inter.variable} flex flex-col gap-4'}> 
        <TopNav />
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
